### ISSUE TITLE
SetConfiguration does not pass XML

### ISSUE THREAD

**Issue by rposener** [Microsoft/Reporting-Services#81] opened 2018-04-11 17:00 UTC
Hi,

It seems that in my custom IAuthenticationExtension2, IExtension class - the call to SetConfiguration is only passing the innerText of all nodes in the <Configuration> element on SSRS 2017.  Works fine in SSRS 2016.  This makes it impossible to configure my extension.  

Is this a bug?  Or fixed by a certain CU?  I cannot find any mention of it.

**Comment by rposener** [comment] 2018-04-11 20:11
Just a quick clarification: RSPortal.exe appears to pass the innerText instead of the innerXML for the configuration.  The ReportingServicesService.exe appears to pass the innerXML so that the configuration can be read properly.

**Comment by SLazaroc** [comment] 2018-04-29 22:55
Hello All, I have the same problem, Any updates on this issue?

**Comment by jtarquino** [comment] 2018-04-30 14:40
We have identified it as a bug and it will be fixed in future versions of the product

**Closed by jtarquino** 2018-04-30 14:40 UTC

**Comment by cgillam** [comment] 2018-06-06 23:50
This issue should be left open until the bug is fixed. I am experiencing this same problem and perusing the open issues and not seeing a problem I continued to struggle with it. 

Furthermore, the documentation on seeing up custom auth should absolutely note in IT that custom auth configuration data IS NOT SUPPORTED! The instructions and documentation and lack of open bug reports indicate this isn't an issue when in fact it is a real issue that breaks upgrades from 2016 to 2017 that use custom auth.

**Comment by jtarquino** [comment] 2018-06-07 16:44
This project handles the sample code release, bugs and issues, being a product issue we have closed the item.
For the product issues I would recommend you to contact support and they can help you to identify the best way to get the product fix.
You can also use https://powerbi.microsoft.com/en-us/support/

**Comment by Et3rnal** [comment] 2019-07-05 08:24
Has this been fixed?

**Comment by jtarquino** [comment] 2019-07-05 15:30
Yes PBIRS may release has a fix for it

**Comment by robotbroken** [comment] 2019-07-09 18:25
Will this also be fixed in SSRS 2017 or only in PBIRS?

**Comment by jtarquino** [comment] 2019-07-09 21:52
Unlikely, but it will be in the next version of SSRS

**Comment by Et3rnal** [comment] 2019-07-10 09:07
In my case, it's not passing anything! I would be happy even with inner text only :D
can someone help or point me to what I need to do just in case I missed something?

**Comment by robotbroken** [comment] 2019-07-10 09:15
In my case I have some XML like:

```
<Configuration>
    <SecurityOptions>
        <DatabaseConnStr>Server:blah;User:blah;</DatabaseConnStr>
    </SecurityOptions>
</Configuration>
```

I would expect to get everything inside of  the `<Configuration>` tag but the only thing that gets passed in the `configuration` parameter is `Server:blah;User:blah;` because innerText strips out the XML tags. If you're trying to use XML attributes to store your config values then I'm pretty sure they'd get removed.

**Comment by Et3rnal** [comment] 2019-07-17 01:06
My issue was creating new <Extention> tag instead of using the one under <Authentication>, however, I had the complete XML, not text only! I just tidy things up and today all I'm getting is the innerText like you! If I figure out what was it make it work Ill post it here!!!

**Comment by wpraet** [comment] 2022-05-03 18:51
> My issue was creating new tag instead of using the one under , however, I had the complete XML, not text only! I just tidy things up and today all I'm getting is the innerText like you! If I figure out what was it make it work Ill post it here!!!

Did you figure out how to make it work? I'm using SQL Server 2019 Reporting Services and the issue is still there. In fact I don't even get innerText :-)

**Comment by Et3rnal** [comment] 2022-05-04 02:48
> > My issue was creating new tag instead of using the one under , however, I had the complete XML, not text only! I just tidy things up and today all I'm getting is the innerText like you! If I figure out what was it make it work Ill post it here!!!
> 
> Did you figure out how to make it work? I'm using SQL Server 2019 Reporting Services and the issue is still there. In fact I don't even get innerText :-)

No sorry, it stopped working again and I was able to figure out what cause it to work/stop! I gave up. So you are on the latest release and this is still not fixed!
